### PR TITLE
Added fullTemplateTypeCheck to build-public-library

### PR DESCRIPTION
**Pull request by Blackbaud-DeniseCisneros**
Addresses https://github.com/blackbaud/skyux2-docs/issues/834

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-template-check](https://developer.blackbaud.com/skyux?_sp.spa=pr-template-check)

**Comment by blackbaud-johnly** [comment]
While reviewing https://github.com/blackbaud/skyux-sdk-builder/pull/211, I noticed that the changelog description there has more info about `fullTemplateTypeCheck` than we are providing here:
```We've set the Angular Compiler to run `fullTemplateTypeCheck` which ensures that your SPA and library component HTML templates are referencing `public` properties in the component's class. This change may cause your builds to fail if you have bindings to invalid properties. Read [Angular's documentation](https://angular.io/guide/angular-compiler-options#fulltemplatetypecheck) for more information about template type checking. [#181](https://github.com/blackbaud/skyux-sdk-builder/pull/181)```
I asked Steve about incorporating the additional info from this changelog into the docs, and he agreed that it was a good idea. Do you mind handling that @Blackbaud-DeniseCisneros? I can work on it if you don't have bandwidth today.

**Comment by Blackbaud-DeniseCisneros** [comment]
@blackbaud-johnly I'll make that update now. Thanks for pointing that out!

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-template-check](https://developer.blackbaud.com/skyux?_sp.spa=pr-template-check)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-template-check](https://developer.blackbaud.com/skyux?_sp.spa=pr-template-check)

**Pull request merged**
