### PR TITLE
Update page title guidelines

### PR DESCRIPTION
**Pull request by blackbaud-johnly**

### CODE REVIEW

**Comment by Blackbaud-MattGregg** [comment]
@blackbaud-johnly  @Blackbaud-ToddRoberts  I'm fine with giving that direction a go to try to keep up this idea. It could be written along the lines of use a title with format using the <Page title> - <Company, product, site identifier> (e.g. Gifts - Blackbaud). 

Hopefully teams will start seeing this more in applications and just get the format though to be honest getting the page title set to anything is going to be a win at this point.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-MattGregg @Blackbaud-ToddRoberts ... I updated the docs based on Matt's response to Todd's feedback. Please just let me know if this looks OK to you know. I'll hold off on merging the PR until I hear back from you. Thanks.

**Comment by blackbaud-johnly** [comment]
Thanks, @Blackbaud-MattGregg. I updated again. Hopefully this works now.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-MattGregg do the changes look OK to you now? Just waiting on you to sign off before we merge. Thanks!

**Comment by Blackbaud-MattGregg** [comment]
@blackbaud-johnly Looks good to me. Thanks.

**Pull request merged**
