### PR TITLE
Document disabled property for autocomplete

### PR DESCRIPTION
**Pull request by blackbaud-johnly**
Addresses https://github.com/blackbaud/skyux2-docs/issues/953.

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920](https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920](https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920](https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920)

**Comment by blackbaud-johnly** [comment]
Waiting for the feature to be released. It has been merged but not released.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920](https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920](https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920](https://developer.blackbaud.com/skyux?_sp.spa=pr-autocomplete-disabled-061920)

**Pull request merged**
