### PR TITLE
Packages cleanup

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions](https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions](https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions](https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions](https://developer.blackbaud.com/skyux?_sp.spa=pr-gh-actions)

**Pull request merged**
